# Generated by Django 5.0.6 on 2024-07-10 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=200, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
