# Generated by Django 5.0.6 on 2024-07-15 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_nonveg',
            field=models.BooleanField(default=False, verbose_name='is Non veg'),
        ),
        migrations.AddField(
            model_name='food',
            name='is_veg',
            field=models.BooleanField(default=True, verbose_name='is Veg'),
        ),
        migrations.AlterField(
            model_name='food',
            name='slug',
            field=models.SlugField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
